import Header from '@/components/layout/header/header'

import Footer from '@/components/layout/footer/footer'
import { hidi, montserrat } from '@/lib/fonts'
import type { Metadata } from "next"
import "./globals.css"

export const metadata: Metadata = {
  title: "Parsec",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body
        className={`${montserrat.variable} ${hidi.variable} antialiased`}
      >
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  )
}
