
import Footer from '@/components/layout/footer/footer'
import Header from '@/components/layout/header/header'
import { siteTitle } from '@/lib/constans'
import { hidi, montserrat } from '@/lib/fonts'
import type { Metadata } from "next"
import { Toaster } from 'sonner'
import "./globals.css"
import Provider from './provider'

export const metadata: Metadata = {
  title: siteTitle,
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body
        className={`${montserrat.variable} ${hidi.variable} antialiased`}
      >
        <Provider>
          <Header />
          {children}
          <Footer />
        </Provider>
      </body>
    </html>
  )
}
